version: '3.7'

x-node-env:
  &kz-env
    LOCAL_USER: "true"
    TERM: screen-256color
    KAZOO_COOKIE: change_me
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/kazoo/_rel/kazoo/bin"

x-devol-cfg:
  &kz-vol
    - type: bind
      source: ${KAZOO_SRC}
      target: /opt/kazoo
    - type: volume
      source: kazoo-sounds
      target: /opt/sounds
      read_only: true
    - type: bind
      source: ${wKazoo}/monster-ui
      target: /opt/monster-ui
      read_only: true
    - type: bind
      source: ${DOCKER_ROOT}/scripts
      target: /opt/scripts
    - type: bind
      source: ${DOCKER_ROOT}/files/kazoo-config.ini
      target: /etc/kazoo/config.ini
    - type: tmpfs
      target: /etc/kazoo/ra

volumes:
    kazoo-sounds:
      name: kz-master-kazoo-sounds
    couchdb-data:
      name: kz-master-couchdb-data

networks:
  kazoo:
    attachable: true

services:
  couchdb:
    image: couchdb:latest
    hostname: 'couchdb.2600hz-test.com'
    environment:
      # make sure couchdb using the above hostname
      # by setting NODENAME to hostname, otherwise db's are
      # are created with random docker hostname/container name
      NODENAME: 'couchdb.2600hz-test.com'
    volumes:
      - type: bind
        source: ${DOCKER_ROOT}/files/couchdb-cluster.ini
        target: /opt/couchdb/etc/local.d/20-cluster.ini
      - type: volume
        source: couchdb-data
        target: "/opt/couchdb/data"
    ports:
      - target: 9100
        published: 9100
      - target: 5984
        published: 5984
      - target: 5986
        published: 5986
    networks:
      kazoo:

  rabbitmq:
    image: rabbitmq:3-management
    hostname: 'rabbitmq.2600hz-test.com'
    environment:
        # This is needed to allow distributed Erlang shell
        # and start of rabbitmq
        RABBITMQ_USE_LONGNAME: 'true'
    volumes:
        # enabling rabbitmq_consistent_hash_exchange plugin
        - type: bind
          source: ${DOCKER_ROOT}/files/rabbitmq-entrypoint.sh
          target: /rabbitmq-entrypoint.sh
        # without this sometimes docker/rabbitmq veing stupid
        # and causing rabbitmq to behave strangely (not creating exchange or etc)
        - type: tmpfs
          target: /var/lib/rabbitmq
    entrypoint: /rabbitmq-entrypoint.sh
    command: ["rabbitmq-server"]
    ports:
      - target: 15672 # management UI
        published: 15672
      - target: 5672 # AMQP port
        published: 5672
    networks:
      kazoo:

  kazoo_apps:
    image: icehess/kz-dev-env:21
    hostname: 'kazoo_apps.2600hz-test.com'
    environment:
       << : *kz-env
       KAZOO_NODE: kazoo_apps
       NODE_NAME: kazoo_apps
       REL: kazoo_apps
    volumes: *kz-vol
    tty: true
    command: ["bash"]
    ports:
      - target: 11500 # Erlang
        published: 11500
      - target: 8000 # Crossbar
        published: 8000
      - target: 5555 # Websocket
        published: 5555
      - target: 25 # Fax SMTP
      - target: 8001 # GraphQL
    networks:
      kazoo:

  kazoo_sounds:
    image: 'alpine:latest'
    command: ["/bin/ash"]
    volumes:
      - type: volume
        source: kazoo-sounds
        target: /opt/kazoo-sounds
    tty: true

  monster-ui:
    image: node:10.16.0-alpine
    hostname: 'portal.2600hz-test.com'
    environment:
       TERM: screen-256color
       LC_CTYPE: en_US.UTF-8
       LANG: en_US.UTF-8
    volumes:
      - type: bind
        source: ${DOCKER_ROOT}/files/monster-entrypoint.sh
        target: /monster-entrypoint.sh
      - type: bind
        source: ${wKazoo}/monster-ui
        target: "/opt/monster-ui"
    tty: true
    entrypoint: /monster-entrypoint.sh
    command: ["/opt/monster-ui/node_modules/gulp/bin/gulp.js", "serve-dev"]
    ports:
      - target: 3000
    networks:
      kazoo:

  mailcatcher:
    image: 'schickling/mailcatcher'
    hostname: 'mail.2600hz-test.com'
    ports:
      - target: 1080
      - target: 1025
    networks:
      - kazoo
